20BEC119
Siddharth Agarwal
Exp 3

Task 1
1. Define the following 2-D (i.e. two feature) Data
X1 X2
1.4 1.65
1.6 1.975
-1.4 -1.775
-2 -2.525
-3 -3.95
2.4 3.075
1.5 2.025
2.3 2.75
-3.2 -4.05
-4.1 -4.85
1.4 1.65
2. Standardize the data.
3. Find the two principal components.
4. Observe the result. (in terms of covariance and explained parameters)

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

#Importing datsets
dataset=pd.read_csv("exe1.csv")
x=dataset.iloc[:,0:2].values
x

array([[ 1.4  ,  1.65 ],
       [ 1.6  ,  1.975],
       [-1.4  , -1.775],
       [-2.   , -2.525],
       [-3.   , -3.95 ],
       [ 2.4  ,  3.075],
       [ 1.5  ,  2.025],
       [ 2.3  ,  2.75 ],
       [-3.2  , -4.05 ],
       [-4.1  , -4.85 ],
       [ 1.4  ,  1.65 ]])

In [5]:
#feature scaling
ss=StandardScaler()
x1=ss.fit_transform(x)
x1

array([[ 0.71467469,  0.68944344],
       [ 0.79966303,  0.80059385],
       [-0.47516209, -0.48191086],
       [-0.73012711, -0.7384118 ],
       [-1.15506882, -1.22576359],
       [ 1.13961639,  1.17679523],
       [ 0.75716886,  0.81769391],
       [ 1.09712222,  1.06564482],
       [-1.24005716, -1.25996372],
       [-1.6225047 , -1.53356472],
       [ 0.71467469,  0.68944344]])

In [7]:
#applying pca
pca=PCA(n_components=2)
x2=pca.fit_transform(x1)
x2

array([[-9.92861449e-01, -1.78411867e-02],
       [-1.13155249e+00,  6.58188095e-04],
       [ 6.76752773e-01, -4.77210102e-03],
       [ 1.03841382e+00, -5.85815884e-03],
       [ 1.68350274e+00, -4.99887514e-02],
       [-1.63795037e+00,  2.62894059e-02],
       [-1.11359614e+00,  4.27976746e-02],
       [-1.52930724e+00, -2.22578851e-02],
       [ 1.76778171e+00, -1.40760597e-02],
       [ 2.23167809e+00,  6.28900608e-02],
       [-9.92861449e-01, -1.78411867e-02]])

In [9]:
#Finding principal components
explained_variance=pca.explained_variance_
explained_variance_ratio=pca.explained_variance_ratio_
print(explained_variance," ",explained_variance_ratio)

[2.19896355e+00 1.03644978e-03]   [9.99528886e-01 4.71113537e-04]


2)Write a program to perform dimensionality reduction using Principal Components Analysis (PCA). Download the dataset from
https://github.com/stavanR/Machine-Learning-Algorithms-Dataset.git.Dataset File name- Wine.csv

In [10]:
#Loading dataset
dataset=pd.read_csv('wine.csv')
x=dataset.iloc[:,0:13].values
x

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [12]:
#Feature Scaling
ss=StandardScaler()
x1=ss.fit_transform(x)
x1

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  0.36217728,
         1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 0.33275817,  1.74474449, -0.38935541, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 0.20923168,  0.22769377,  0.01273209, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.39508604,  1.58316512,  1.36520822, ..., -1.52437837,
        -1.42894777, -0.59516041]])

In [16]:
#applying PCA
pca=PCA(n_components=2)
x2=pca.fit_transform(x1)
x2

array([[ 3.31675081, -1.44346263],
       [ 2.20946492,  0.33339289],
       [ 2.51674015, -1.0311513 ],
       [ 3.75706561, -2.75637191],
       [ 1.00890849, -0.86983082],
       [ 3.05025392, -2.12240111],
       [ 2.44908967, -1.17485013],
       [ 2.05943687, -1.60896307],
       [ 2.5108743 , -0.91807096],
       [ 2.75362819, -0.78943767],
       [ 3.47973668, -1.30233324],
       [ 1.7547529 , -0.61197723],
       [ 2.11346234, -0.67570634],
       [ 3.45815682, -1.13062988],
       [ 4.31278391, -2.09597558],
       [ 2.3051882 , -1.66255173],
       [ 2.17195527, -2.32730534],
       [ 1.89897118, -1.63136888],
       [ 3.54198508, -2.51834367],
       [ 2.0845222 , -1.06113799],
       [ 3.12440254, -0.78689711],
       [ 1.08657007, -0.24174355],
       [ 2.53522408,  0.09184062],
       [ 1.64498834,  0.51627893],
       [ 1.76157587,  0.31714893],
       [ 0.9900791 , -0.94066734],
       [ 1.77527763, -0.68617513],
       [ 1.23542396,  0.08980704],
       [ 2.18840633,

In [20]:
#Finding principal components
explained_variance=pca.explained_variance_
explained_variance_ratio=pca.explained_variance_ratio_
print(explained_variance," ",explained_variance_ratio)

[4.73243698 2.51108093]   [0.36198848 0.1920749 ]


3)Repeat the steps of task #2 for the dataset from https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data Use first two principal components. Visualise the transformed data.

In [25]:
#Importing datsets
dataset=pd.read_csv("iris.csv")
x=dataset.iloc[:,:-1].values
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [26]:
#Feature Scaling
ss=StandardScaler()
x1=ss.fit_transform(x)
x1

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [27]:
#applying PCA
pca=PCA(n_components=2)
x2=pca.fit_transform(x1)
x2

array([[-2.26470281,  0.4800266 ],
       [-2.08096115, -0.67413356],
       [-2.36422905, -0.34190802],
       [-2.29938422, -0.59739451],
       [-2.38984217,  0.64683538],
       [-2.07563095,  1.48917752],
       [-2.44402884,  0.0476442 ],
       [-2.23284716,  0.22314807],
       [-2.33464048, -1.11532768],
       [-2.18432817, -0.46901356],
       [-2.1663101 ,  1.04369065],
       [-2.32613087,  0.13307834],
       [-2.2184509 , -0.72867617],
       [-2.6331007 , -0.96150673],
       [-2.1987406 ,  1.86005711],
       [-2.26221453,  2.68628449],
       [-2.2075877 ,  1.48360936],
       [-2.19034951,  0.48883832],
       [-1.898572  ,  1.40501879],
       [-2.34336905,  1.12784938],
       [-1.914323  ,  0.40885571],
       [-2.20701284,  0.92412143],
       [-2.7743447 ,  0.45834367],
       [-1.81866953,  0.08555853],
       [-2.22716331,  0.13725446],
       [-1.95184633, -0.62561859],
       [-2.05115137,  0.24216355],
       [-2.16857717,  0.52714953],
       [-2.13956345,

In [28]:
#Finding principal components
explained_variance=pca.explained_variance_
explained_variance_ratio=pca.explained_variance_ratio_
print(explained_variance," ",explained_variance_ratio)

[2.93808505 0.9201649 ]   [0.72962445 0.22850762]


Excersise 1:
Principal Component Analysis with Scikit-Learn. The dataset can be downloaded from: https://www.kaggle.com/nirajvermafcb/principalcomponent-analysis-with-scikit-learn

In [29]:
#Loading dataset
dataset=pd.read_csv('wine.csv')
x=dataset.iloc[:,[0,2,3,4,5,6,7,8,9]].values
x

array([[14.23,  2.43, 15.6 , ...,  0.28,  2.29,  5.64],
       [13.2 ,  2.14, 11.2 , ...,  0.26,  1.28,  4.38],
       [13.16,  2.67, 18.6 , ...,  0.3 ,  2.81,  5.68],
       ...,
       [13.27,  2.26, 20.  , ...,  0.43,  1.35, 10.2 ],
       [13.17,  2.37, 20.  , ...,  0.53,  1.46,  9.3 ],
       [14.13,  2.74, 24.5 , ...,  0.56,  1.35,  9.2 ]])

In [30]:
#Feature Scaling
ss=StandardScaler()
x1=ss.fit_transform(x)
x1

array([[ 1.51861254,  0.23205254, -1.16959318, ..., -0.65956311,
         1.22488398,  0.25171685],
       [ 0.24628963, -0.82799632, -2.49084714, ..., -0.82071924,
        -0.54472099, -0.29332133],
       [ 0.19687903,  1.10933436, -0.2687382 , ..., -0.49840699,
         2.13596773,  0.26901965],
       ...,
       [ 0.33275817, -0.38935541,  0.15166079, ...,  0.5491078 ,
        -0.4220751 ,  2.22423597],
       [ 0.20923168,  0.01273209,  0.15166079, ...,  1.3548884 ,
        -0.22934584,  1.83492299],
       [ 1.39508604,  1.36520822,  1.50294326, ...,  1.59662258,
        -0.4220751 ,  1.79166599]])

In [31]:
#applying PCA
pca=PCA(n_components=2)
x2=pca.fit_transform(x1)
x2

array([[ 2.81260202,  1.08512032],
       [ 1.50503941, -1.19721061],
       [ 2.24444201,  0.50762123],
       [ 3.61425589,  1.46948929],
       [ 1.06900752,  1.40409364],
       [ 2.72068964,  1.07680752],
       [ 1.66749352,  0.42081525],
       [ 1.22523901,  1.34163326],
       [ 2.34513437,  0.04625918],
       [ 2.25074956,  0.23312257],
       [ 2.70696582,  0.30139328],
       [ 0.9163189 ,  0.05727716],
       [ 1.34801733, -0.02763013],
       [ 3.23216994,  0.24957383],
       [ 3.9119885 ,  0.62292598],
       [ 1.57572481,  1.52275709],
       [ 2.01335476,  2.01710857],
       [ 1.63954726,  1.641985  ],
       [ 2.820158  ,  1.52814706],
       [ 2.29474484,  0.4742154 ],
       [ 2.89814938,  0.65003966],
       [ 1.01909242,  0.13611297],
       [ 1.51251189, -0.29744152],
       [ 0.57285717, -0.45845045],
       [ 0.84026822,  0.13042018],
       [ 0.47031764,  2.29306948],
       [ 1.18063986,  0.15934131],
       [ 0.47192454, -0.96496435],
       [ 1.49465742,

In [32]:
#Finding principal components
explained_variance=pca.explained_variance_
explained_variance_ratio=pca.explained_variance_ratio_
print(explained_variance," ",explained_variance_ratio)

[3.21539496 1.87966849]   [0.35525899 0.20767873]


Conclusion: We have learnt about Principal Component Analysis in depth and we have also
worked various datasets provided and also available publicly in various archives and sites.
We have worked upon why do we use this specific technique and how it is effective in
reducing the dimensionality of the dataset. We have also understood the concept of the
explained variance and explained variance ratio in PCA.